# Generated by Django 4.1.3 on 2023-07-26 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Join_date', models.DateField(default=datetime.datetime.now)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Experience', models.IntegerField()),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('Qualification', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=20)),
                ('classes', models.CharField(max_length=30)),
                ('About', models.CharField(max_length=300)),
                ('Premium', models.BooleanField(default=False)),
                ('Teaching_mode', models.CharField(max_length=10)),
                ('Phone_number', models.CharField(max_length=12)),
                ('Age', models.IntegerField(default=0)),
                ('Fee', models.CharField(default=0, max_length=5)),
                ('Photo', models.ImageField(null=True, upload_to='images/')),
                ('Pincode', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.pincodes')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_unlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_date', models.DateField(default=datetime.datetime.now)),
                ('Teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
