# Generated by Django 4.1.3 on 2026-04-05 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('experience', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=20)),
                ('classes', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('teaching_mode', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=12)),
                ('age', models.IntegerField(default=0)),
                ('fee', models.CharField(default=0, max_length=5)),
                ('photo', models.ImageField(default=None, null=True, upload_to='teacherphotos/')),
                ('slug', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_unlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_date', models.DateField(default=datetime.datetime.now)),
                ('Teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher')),
            ],
        ),
    ]
