# Generated by Django 4.1.3 on 2024-04-13 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teacher', '0002_alter_teacher_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Photo',
            field=models.ImageField(null=True, upload_to='teacherphotos/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='User_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
