# Generated by Django 4.1.3 on 2026-04-13 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_alter_teacher_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teacher_unlock',
            name='unlock_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
