# Generated by Django 4.1.3 on 2024-04-14 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_alter_teacher_photo_alter_teacher_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='About',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Fee',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Join_date',
            new_name='join_date',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Pincode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Qualification',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Premium',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Teaching_mode',
            new_name='teaching_mode',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='User_id',
            new_name='user_id',
        ),
    ]
