# Generated by Django 4.1.3 on 2024-04-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_rename_about_teacher_about_rename_age_teacher_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
