# Generated by Django 4.1.3 on 2026-04-13 05:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_alter_teacher_join_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teacher',
            index=django.contrib.postgres.indexes.GinIndex(fields=['subject', 'classes', 'location', 'qualification'], name='teacher_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
