# Generated by Django 4.1.3 on 2024-04-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_teacher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='teacherphotos/'),
        ),
    ]
