# Generated by Django 4.1.3 on 2023-12-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.IntegerField()),
                ('roleName', models.CharField(max_length=55)),
            ],
        ),
    ]
