# Generated by Django 4.1.3 on 2024-04-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(default=None, null=True, upload_to='profilepic'),
        ),
    ]
