# Generated by Django 4.1.3 on 2024-04-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0004_alter_customuser_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.AlterField(
            model_name='role',
            name='roleId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
