# Generated by Django 4.1.3 on 2026-04-05 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tuitionmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tuition_unlock',
            name='Tuition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuitionmanager.tuitions'),
        ),
        migrations.AddField(
            model_name='tuition_unlock',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
