# Generated by Django 4.1.3 on 2023-08-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('Tuitionmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitions',
            name='pincode',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.pincodes'),
        ),
    ]
