# Generated by Django 4.1.3 on 2024-03-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuitionmanager', '0002_alter_tuitions_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitions',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tuitions',
            name='locality',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
