# Generated by Django 4.1.3 on 2026-04-13 03:50

import datetime
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuitionmanager', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition_unlock',
            name='unlock_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tuitions',
            name='posted_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddIndex(
            model_name='tuitions',
            index=django.contrib.postgres.indexes.GinIndex(fields=['subject', 'course', 'locality'], name='tuition_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
