# Generated by Django 4.1.3 on 2026-04-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuitionmanager', '0003_alter_tuition_unlock_unlock_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tuitions',
            index=models.Index(fields=['user_id', '-posted_date', '-id'], name='tuition_user_date_idx'),
        ),
    ]
