# Generated by Django 4.1.3 on 2023-07-26 12:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('plan_description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('plan_code', models.CharField(max_length=20, unique=True)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime.now)),
                ('Razor_Order_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='Created', max_length=20)),
                ('Credited', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.plan')),
            ],
        ),
    ]
