# Generated by Django 4.1.3 on 2026-04-05 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime.now)),
                ('Razor_Order_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='Created', max_length=20)),
                ('Credited', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('plan_description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('plan_code', models.CharField(max_length=20, unique=True)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
