# Generated by Django 4.1.3 on 2023-07-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pincodes',
            fields=[
                ('Pincode', models.IntegerField(primary_key=True, serialize=False)),
                ('Devision', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
                ('Circle', models.CharField(max_length=100)),
                ('Taluk', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
            ],
        ),
    ]
