# Generated by Django 4.1.3 on 2026-04-13 03:50

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pincodes',
            index=django.contrib.postgres.indexes.GinIndex(fields=['Devision', 'District', 'State', 'Taluk'], name='pincode_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
