# Generated by Django 4.1.3 on 2026-04-13 04:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_pincodes_pincode_trgm_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pincodes',
            name='pincode_trgm_idx',
        ),
        migrations.AddIndex(
            model_name='pincodes',
            index=django.contrib.postgres.indexes.GinIndex(fields=['Devision', 'District', 'State', 'Taluk', 'Region'], name='pincode_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
